//! The brief for one gap: what to build, and what proves it was built.
//!
//! A scan says a primitive is at 0 and names the paths it looked in. That is a
//! finding, and a finding is not work. This turns each one into something
//! pasteable into whatever agent the reader already has open, in the words that
//! defined the requirement rather than a summary of them, because a paraphrased
//! requirement is how a check ends up testing something adjacent.
//!
//! The generic half comes from `config/contracts.json`, vendored from
//! harness-kit by `dev/vendor-contracts.py`. The specific half is this
//! repository's own evidence and shortfall, which the scan already produced.
//! Neither half is rewritten in this file.
//!
//! What this deliberately is not. `contracts.yaml` says trunnion does not read it
//! and must not, and that line is what keeps prescription and scoring apart:
//! harness-kit refuses to infer a level, trunnion refuses to prescribe one. The
//! rule survives here because the contracts are quoted and never measured
//! against. Nothing in this module returns a number, `scan` and `scorer` do not
//! reference it, and `tests/invariants.rs` fails the build if that changes,
//! because an architectural rule kept by intention is kept by nothing.

use crate::scan::ScanReport;
use crate::workspace::Risk;
use crate::Fault;
use std::collections::HashMap;

/// The vendored contracts, compiled in. A brief has to be printable on a
/// machine that has never seen harness-kit, which is every machine that
/// installs a release binary.
const CONTRACTS_JSON: &str = include_str!("../config/contracts.json");

/// The twelve keys, in spec order, indexed by primitive number minus one. The
/// scan reports numbers and the contracts are keyed by name; this is the only
/// place the two vocabularies meet.
pub const KEYS: [&str; 12] = [
    "instruction",
    "context_delivery",
    "context_management",
    "tool_interface",
    "execution_environment",
    "durable_state",
    "orchestration",
    "sub_agents",
    "skills",
    "verification",
    "observability",
    "governance",
];

/// Spec 0.2.0-draft section 2.2. The ablation-derived sequence, which breaks a
/// tie only where business risk does not already decide the order.
const ABLATION: [&str; 6] = [
    "execution_environment",
    "tool_interface",
    "context_management",
    "durable_state",
    "orchestration",
    "instruction",
];

/// Capability without trust is a liability, so these outrank everything else
/// for work that leaves the building.
const TRUST_LAYER: [&str; 3] = ["verification", "observability", "governance"];

pub struct Contract {
    pub key: String,
    pub id: String,
    pub targets: HashMap<String, Target>,
    pub anti_pattern: String,
    pub cost: String,
}

#[derive(Default)]
pub struct Target {
    pub requirement: String,
    pub artifact: String,
    pub check: String,
}

pub struct Contracts {
    pub contracts_version: String,
    pub spec_version: String,
    by_key: HashMap<String, Contract>,
}

impl Contracts {
    /// Parse the vendored copy. A failure here is a build defect rather than
    /// anything the operator did, so the fix says so instead of asking them to
    /// check a path they never chose.
    pub fn load() -> Result<Contracts, Fault> {
        let doc: serde_json::Value = serde_json::from_str(CONTRACTS_JSON).map_err(|e| {
            Fault::new(
                format!("the vendored contracts do not parse: {e}"),
                "report this as a bug; config/contracts.json is compiled into the binary and is generated by dev/vendor-contracts.py, so a parse failure is a bad vendoring and not a bad install",
            )
        })?;
        let mut by_key = HashMap::new();
        let list = doc["contracts"].as_array().ok_or_else(|| {
            Fault::new(
                "the vendored contracts carry no contracts array",
                "report this as a bug; re-vendor with dev/vendor-contracts.py <harness-kit>/contracts.yaml",
            )
        })?;
        for c in list {
            let key = c["key"].as_str().unwrap_or_default().to_string();
            let mut targets = HashMap::new();
            if let Some(map) = c["targets"].as_object() {
                for (level, body) in map {
                    targets.insert(
                        level.clone(),
                        Target {
                            requirement: text(&body["requirement"]),
                            artifact: text(&body["artifact"]),
                            check: text(&body["check"]),
                        },
                    );
                }
            }
            by_key.insert(
                key.clone(),
                Contract {
                    key,
                    id: c["id"].as_str().unwrap_or_default().to_string(),
                    targets,
                    anti_pattern: text(&c["anti_pattern"]),
                    cost: text(&c["cost"]),
                },
            );
        }
        if by_key.len() != KEYS.len() {
            return Err(Fault::new(
                format!(
                    "the vendored contracts carry {} primitives and the spec has {}",
                    by_key.len(),
                    KEYS.len()
                ),
                "report this as a bug; re-vendor with dev/vendor-contracts.py, which refuses a file that is not twelve",
            ));
        }
        Ok(Contracts {
            contracts_version: text(&doc["contracts_version"]),
            spec_version: text(&doc["spec_version"]),
            by_key,
        })
    }

    pub fn get(&self, key: &str) -> Option<&Contract> {
        self.by_key.get(key)
    }
}

fn text(v: &serde_json::Value) -> String {
    v.as_str().unwrap_or_default().to_string()
}

/// Where a primitive sits in the queue. Lower is sooner.
///
/// Execution environment is exempt from everything and sequenced first,
/// because its gaps are security findings rather than maturity observations.
/// Then, for work that is client facing or regulated, the trust layer, because
/// a capable system nobody can audit is a liability rather than an asset. Only
/// where risk does not decide does the ablation sequence break the tie.
///
/// Defaulting an unstated risk to internal is the conservative choice: it
/// declines to reorder the queue on an assumption the assessment did not make.
pub fn rank(key: &str, risk: Risk, all_keys: &[&str]) -> usize {
    if key == "execution_environment" {
        return 0;
    }
    if matches!(risk, Risk::ClientFacing | Risk::Regulated) {
        if let Some(i) = TRUST_LAYER.iter().position(|k| *k == key) {
            return 1 + i;
        }
    }
    const BASE: usize = 10;
    if let Some(i) = ABLATION.iter().position(|k| *k == key) {
        return BASE + i;
    }
    BASE + ABLATION.len() + all_keys.iter().position(|k| *k == key).unwrap_or(0)
}

/// One gap, ready to be ordered and printed.
pub struct Gap {
    pub primitive: u8,
    pub key: &'static str,
    pub name: &'static str,
    pub current: u8,
    pub target: u8,
    pub evidence: String,
    pub gap: String,
}

/// The gaps in a scan, in the order they should be worked.
///
/// A primitive already at the target is not a gap.
///
/// The target is the next level anything is actually prescribed for, which is
/// 3 and then 4. Levels 0 to 2 describe not having done the thing, so the
/// contracts carry no requirements there and a brief aimed at 2 would be an
/// instruction with nothing behind it: exactly the shape of advice this whole
/// model exists to replace. From anywhere below defined, the unit of work is
/// the artifact and the check that names it, which is what the level 3
/// contract describes. Above 4 nothing is prescribed either, because level 5
/// is emergent and a prescribed 5 degenerates into "capture failures as
/// rules", the vapidity that schema exists to prevent.
pub fn gaps(report: &ScanReport, risk: Risk) -> Vec<Gap> {
    let all: Vec<&str> = KEYS.to_vec();
    // `overall` is the minimum the report already computed. Recomputing it
    // here would be a second place for the minimum rule to live, and a second
    // place for it to stop agreeing with the first.
    const DEFINED: u8 = 3;
    const HIGHEST_PRESCRIBED: u8 = 4;
    let target = if report.overall < DEFINED {
        DEFINED
    } else {
        HIGHEST_PRESCRIBED
    };
    let mut out: Vec<Gap> = report
        .findings
        .iter()
        .filter(|f| f.score < target)
        .filter_map(|f| {
            let i = usize::from(f.primitive).checked_sub(1)?;
            Some(Gap {
                primitive: f.primitive,
                key: KEYS.get(i)?,
                name: f.name,
                current: f.score,
                target,
                evidence: f.evidence.clone(),
                gap: f.gap.clone(),
            })
        })
        .collect();
    out.sort_by_key(|g| (rank(g.key, risk, &all), g.primitive));
    out
}

/// The paste-into-your-agent brief for one gap.
///
/// Deliberately plain text and vendor neutral: it goes into Claude Code,
/// Codex, Cursor or a chat window without editing. The generic half is the
/// contract's own text for the target level, so the requirement and its check
/// are the same words that defined the gap; the specific half is this
/// project's evidence and shortfall. Neither half is paraphrased.
pub fn brief(gap: &Gap, contract: &Contract, project: &str) -> String {
    let mut s = String::new();
    let push = |s: &mut String, line: &str| {
        s.push_str(line);
        s.push('\n');
    };

    push(
        &mut s,
        &format!(
            "Raise primitive {} {} from {} to {} in {project}.",
            gap.primitive, gap.name, gap.current, gap.target
        ),
    );
    push(&mut s, "");
    push(
        &mut s,
        "This is the twelve-primitive agent harness maturity model. The overall level is",
    );
    push(
        &mut s,
        "the minimum across primitives, never the average, so this one is holding the",
    );
    push(
        &mut s,
        "system down. A primitive carried only by a guide caps at 3: to reach 4 the rule",
    );
    push(
        &mut s,
        "must be enforced by something that fails when it is broken.",
    );
    push(&mut s, "");
    push(&mut s, "WHAT IS THERE NOW");
    push(&mut s, &format!("  {}", gap.evidence));
    push(&mut s, "");
    if !gap.gap.is_empty() {
        push(&mut s, "THE GAP");
        push(&mut s, &format!("  {}", gap.gap));
        push(&mut s, "");
    }

    let spec = contract.targets.get(&gap.target.to_string());
    if let Some(spec) = spec {
        if !spec.requirement.is_empty() {
            push(&mut s, &format!("REQUIREMENT FOR LEVEL {}", gap.target));
            push(&mut s, &format!("  {}", spec.requirement));
            push(&mut s, "");
        }
        if !spec.artifact.is_empty() {
            push(&mut s, "ARTIFACT TO PRODUCE");
            push(&mut s, &format!("  {}", spec.artifact));
            push(&mut s, "");
        }
        if !spec.check.is_empty() {
            push(&mut s, "ACCEPTANCE, AND THE ONLY THING THAT COUNTS AS DONE");
            push(&mut s, &format!("  {}", spec.check));
            push(&mut s, "");
        }
    }
    if !contract.anti_pattern.is_empty() {
        push(&mut s, "DO NOT SHIP THIS INSTEAD");
        push(&mut s, &format!("  {}", contract.anti_pattern));
        push(&mut s, "");
    }
    push(&mut s, "RULES FOR THE WORK");
    push(
        &mut s,
        "  Read the code before proposing a change. Smallest diff that actually enforces",
    );
    push(
        &mut s,
        "  the rule; no new dependency for something a few lines can do.",
    );
    push(
        &mut s,
        "  The check must run on every change and must block, not warn. A check that",
    );
    push(
        &mut s,
        "  reports and does not gate leaves this primitive at 3.",
    );
    push(
        &mut s,
        "  Its failure message names the fix, not just the failure, because an agent",
    );
    push(&mut s, "  reads that message and acts on it.");
    push(
        &mut s,
        "  Break the thing deliberately, watch the check go red, and paste that output",
    );
    push(
        &mut s,
        "  into the proof. A check never observed failing has not been shown able to fail.",
    );
    push(
        &mut s,
        "  Then name the check in the instruction file on the rule it carries, and remove",
    );
    push(&mut s, "  that rule's unenforced marker.");
    s
}

/// Every gap in a report, briefed and in order, as one document.
pub fn document(report: &ScanReport, risk: Risk, project: &str) -> Result<String, Fault> {
    let contracts = Contracts::load()?;
    let gaps = gaps(report, risk);
    let mut s = format!(
        "remediation for {project}\n\
         {} gap(s), ordered by business risk at {}, then by what unblocks the most.\n\
         contracts {} against spec {}. Every requirement and check below is the contract's own text.\n",
        gaps.len(),
        risk.as_str(),
        contracts.contracts_version,
        contracts.spec_version
    );
    if gaps.is_empty() {
        s.push_str(
            "\nNothing is below the next reachable level. A static read stops at 3; for 4 and\n\
             above, run trunnion score over a ledger, which reads events rather than files.\n",
        );
        return Ok(s);
    }
    for (n, gap) in gaps.iter().enumerate() {
        s.push_str(&format!(
            "\n{}\n{}. primitive {:02} {} | {} -> {}\n{}\n\n",
            "=".repeat(78),
            n + 1,
            gap.primitive,
            gap.name,
            gap.current,
            gap.target,
            "=".repeat(78)
        ));
        match contracts.get(gap.key) {
            Some(contract) => s.push_str(&brief(gap, contract, project)),
            // A key the scan produced that the contracts do not carry is a
            // drift between the two, and the reader is told which one rather
            // than handed a brief with a silently missing half.
            None => s.push_str(&format!(
                "no contract is vendored for {}, so there is no requirement text to quote.\n\
                 Re-vendor with dev/vendor-contracts.py <harness-kit>/contracts.yaml.\n",
                gap.key
            )),
        }
    }
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_vendored_contracts_carry_twelve_primitives_with_text_to_quote() {
        let c = Contracts::load().unwrap();
        for key in KEYS {
            let contract = c
                .get(key)
                .unwrap_or_else(|| panic!("{key} is not vendored"));
            for level in ["3", "4"] {
                let t = contract
                    .targets
                    .get(level)
                    .unwrap_or_else(|| panic!("{key} has no level {level}"));
                assert!(!t.requirement.is_empty(), "{key} level {level} requirement");
                // The check is the whole point of the contract: a requirement
                // whose check cannot be written is vapid by construction.
                assert!(!t.check.is_empty(), "{key} level {level} check");
            }
        }
    }

    #[test]
    fn execution_environment_outranks_everything_at_every_risk_level() {
        let all = KEYS.to_vec();
        for risk in [Risk::Internal, Risk::ClientFacing, Risk::Regulated] {
            let mine = rank("execution_environment", risk, &all);
            for key in KEYS {
                if key == "execution_environment" {
                    continue;
                }
                assert!(
                    mine < rank(key, risk, &all),
                    "{key} came before execution environment at {}",
                    risk.as_str()
                );
            }
        }
    }

    #[test]
    fn the_trust_layer_rises_only_when_the_work_leaves_the_building() {
        let all = KEYS.to_vec();
        // Internal: the ablation order decides, so tool interface beats
        // verification.
        assert!(
            rank("tool_interface", Risk::Internal, &all)
                < rank("verification", Risk::Internal, &all)
        );
        // Client facing and regulated: capability without trust is a
        // liability, so verification outranks it.
        for risk in [Risk::ClientFacing, Risk::Regulated] {
            assert!(
                rank("verification", risk, &all) < rank("tool_interface", risk, &all),
                "the trust layer did not rise at {}",
                risk.as_str()
            );
        }
    }
}
